services:
  api:
    container_name: server
    build: ./server
    env_file: .env
    restart: always
    command: npm run full
    volumes:
      - ./api:/app/

  client:
    container_name: client
    build: ./client
    command: npm run dev
    restart: always
    environment:
      - VITE_API_URL=http://localhost:5000/graph
    volumes:
      - ./client:/app/

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client
