services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    restart: always

  server:
    container_name: server
    build: ./server
    env_file: .env
    restart: always
    command: npm run full
    volumes:
      - ./api:/app/
    ports:
      - 4000:4000

  client:
    container_name: client
    build: ./client
    command: npm run dev
    restart: always
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./client:/app/
